### ISSUE TITLE
4.6.1 Failing to install on Developer Machine.

### ISSUE THREAD

**Issue by daveaton** [stfx/innodependencyinstaller#19] opened 2016-07-05 11:19 UTC
I had visual studio Update 3 RC on my machine. and it's failing to install 4.6.1 

Here are my product keys.
# Visual Studio 2015 C++ Redistribution Update 3 RC

```
x86 = {03AC7A79-F8AF-38FC-9DA0-98DAB4F4B1CD}
x86 Ver = 14.0.24123

x64 = {21134089-9B59-34C8-BE11-929D26AD5207}
x64 Ver = 14.0.24123
```

I upgrade to the full version of Visual Studio Update 3 and still had the same keys.

http://screencast.com/t/LAVG8WQzC4Mb

I found my keys here  HKEY_CLASSES_ROOT\Installer\Dependencies\Microsoft.VS.VC_RuntimeAdditionalVSU_amd64,v14

HKEY_CLASSES_ROOT\Installer\Dependencies\Microsoft.VS.VC_RuntimeAdditionalVSU_amd86,v14

I do have an AMD processor.. I can image it's different for others.

Currently in vcredist2015 it's looking for

```
vcredist2015_productcode = '{74D0E5DB-B326-4DAE-A6B2-445B9DE1836E}';
vcredist2015_productcode_x64 = '{0D3E9E15-DE7A-300B-96F1-B4AF12B96488}';
     ver = 14.0.23026
```

Is there anyway way we can pull the version number and if it's over 14.0.23026 we can  install anyway ?

Currently my install package works on non developer machines only.  Ones that never installed Visual Studio beyond Visual Studio Update 1

With this current setup when there is a disto for 4.6.2 to the public my installer will fail.

As a temp fix I tried doing something like this..

```
    vcredist2015_url = 'http://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x86.exe';
    vcredist2015_url_x64 = 'http://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x64.exe';

//latest
    vcredist2015_productcode = '{74D0E5DB-B326-4DAE-A6B2-445B9DE1836E}';
    vcredist2015_productcode_x64 = '{0D3E9E15-DE7A-300B-96F1-B4AF12B96488}';

 //Update 3 developers only so far
  vcredist2015Update3RC_productcode = '{03AC7A79-F8AF-38FC-9DA0-98DAB4F4B1CD}';
    vcredist2015Update3RC_productcode_x64 = '{21134089-9B59-34C8-BE11-929D26AD5207}';
  vcredist2015Update3RC_version = '14.0.24123';

procedure vcredist2015();
begin
    if (not IsIA64()) then begin
        if (not msiproduct(GetString(vcredist2015_productcode, vcredist2015_productcode_x64, ''))) then
      //check for developer version
      if (not msiproduct(GetString(vcredist2015Update3RC_productcode, vcredist2015Update3RC_productcode_x64, ''))) then
        AddProduct('vcredist2015' + GetArchitectureString() + '.exe',
          '/passive /norestart',
          CustomMessage('vcredist2015_title' + GetArchitectureString()),
          CustomMessage('vcredist2015_size' + GetArchitectureString()),
          GetString(vcredist2015_url, vcredist2015_url_x64, ''),
          false, false, false);
     end;
    end;
end;
```

But that did not seem to work correctly...

Any ideas ?

**Comment by WildCard-25** [comment] 2016-07-08 18:22
Using Chrome :-

Open Microsoft Visual C++ 2015 Redistributable Page
https://www.visualstudio.com/downloads/download-visual-studio-vs#d-visual-c

Microsoft Visual C++ 2015 Redistributable Update 3

Choose format x86
Click download

Click Chrome's "Show all downloads"
Right-Click on download link and select 'Copy link address'
change 'http' to 'https'
https://download.microsoft.com/download/d/e/c/dec58546-c2f5-40a7-b38e-4df8d60b9764/vc_redist.x86.exe

Choose format x64
Click download

Click Chrome's "Show all downloads"
Right-Click on download link and select 'Copy link address'
change 'http' to 'https'
https://download.microsoft.com/download/2/c/6/2c675af0-2155-4961-b32e-289d7addfcec/vc_redist.x64.exe


Using Explorer :-
Run 'vc_redist.x86.exe'
Get version info
14.0.24210

After installing change to your temp directory (ie. "C:\Users\Username\AppData\Local\Temp")
Open RuntimeMinimum install log (ie. dd_vcredist_x86_20160709013201_000_vcRuntimeMinimum_x86.log)
Get product code from msi location line, about 4 lines down (ie.  ******* Product: C:\ProgramData\Package Cache\{8FD71E98-EE44-3844-9DAD-9CB0BBBC603C}v14.0.24210\packages\vcRuntimeMinimum_x86\vc_runtimeMinimum_x86.msi)
{8FD71E98-EE44-3844-9DAD-9CB0BBBC603C}

Or you can uninstall it instead and the line will be ******* Product: {8FD71E98-EE44-3844-9DAD-9CB0BBBC603C}

Do the same for 'vc_redist.x64.exe'
14.0.24210
{C0B2C673-ECAA-372D-94E5-E89440D087AD}

Update install file.

**Comment by WildCard-25** [comment] 2016-07-09 01:59
Of course if your talking about .NET framework, then vcredist is the wrong file... try dotnetfxversion and dotnetfx46.

**Comment by stfx** [comment] 2017-07-16 16:42
Duplicate of #9

**Closed by stfx** 2017-07-16 16:42 UTC
